Add Candidate Card
hack4impact-uiuc/brink pull request #31
Opened 2022-02-22 05:32 UTC by code-arman

## Summary

Description of PR here...
Closes #85, Closes #22

## Changes

- Item 1
- Item 2
- Item 3

## Screenshots

(Insert image, only for frontend)

## Requests/Responses

### API/Model
*Url*: `/api/users`

*Auth level*: `Open/Registered/Example_Role`

*Method*: `GET/POST/PUT/DELETE`

**Description**
Returns a list of users

**Body**

```json
{
  "data": {
    "attributes": {
      "name": "The Dude",
      "email": "thedudeabides@wee.net",
      "password": "hellopassword"
    }
  },
  "type": "users"
}
```

**Response**
HTTP/1.1 200 OK

```json
{
  "data": {
    "type": "users",
    "id": "4",
    "attributes": {
      "name": "The Dude",
      "email": "thedudeabides@wee.net",
      "last-logged-in": null,
      "created-at": "2016-10-20T17:45:08.190Z",
      "updated-at": "2016-10-20T17:45:08.190Z"
    },
    "links": {
      "self": "/users/4"
    }
  }
```

2022-02-23 21:12 UTC, amit-sawhney requested changes
Good work Arman. Biggest thing is to look a little closer at how the MenuTabs were refactored and match the refactor on main.

2022-02-23 21:12 UTC, amit-sawhney commented on client/src/components/ui/CandidateCard.tsx
> +const CandidateCards: FC<CandidateCardProps> = ({
I think what I am most worried about here is the use of `px` for every single dimension. Normally in SCSS or CSS we would use percentages potentially. Even so, how much extra development do you think it's going to take to make these mobile compatible?

2022-02-23 21:12 UTC, amit-sawhney commented on client/src/components/ui/CandidateCard.tsx
> +interface CandidateCardProps {
Add a space after import groups

2022-02-23 21:12 UTC, amit-sawhney commented on client/src/components/tab/Ballot.tsx
> +    <CandidateCards name="John Doe" party="Republican" />
We should look at mocking out some candidate data soon.

2022-02-23 21:12 UTC, amit-sawhney commented on client/src/pages/Home.tsx
> +import { VoterFAQ, VotingChecklist } from '../components';
Should be above SCSS import

2022-02-23 21:12 UTC, amit-sawhney commented on client/src/components/ui/MenuTabs.tsx
> +import React, { FC, ReactElement, ReactNode } from 'react';
Please refer to how main handled this refactor. We have mismatching designs. We removed the props and added stuff directly to the home page because this component can't really be reused in any compacity and is too specific to what pages it isn't looking for. It makes more sense for the pages to be children if anything. I don't see any use in keeping this a component.

2022-02-23 21:12 UTC, amit-sawhney commented on client/src/components/ui/CandidateCard.tsx
> +        <Box borderRadius="50%" w="100%" h="100%" bgColor="base" m="auto"></Box>
Is there supposed to be anything in this Box? If not Please use `<Box /> form

2022-02-23 21:12 UTC, amit-sawhney commented on client/src/components/ui/CandidateCard.tsx
> +interface CandidateCardProps {
Probably add a TODO that these cards may need more info in the future.

2022-02-23 22:52 UTC, code-arman commented on client/src/components/ui/MenuTabs.tsx
> +import React, { FC, ReactElement, ReactNode } from 'react';
Ohh, i didnt realize this just

2022-02-24 00:53 UTC, code-arman commented on client/src/components/ui/CandidateCard.tsx
> +const CandidateCards: FC<CandidateCardProps> = ({
I pushed a new commit that shows how we can use a chakra ui's simple grid component to help make it mobile responsive

2022-02-24 02:03 UTC, ayanmallik approved these changes
Great job replicating the designs on Figma! The cards look fantastic and it will be exciting to see how you integrate state management/caching into this feature

2022-02-24 02:03 UTC, ayanmallik commented on client/src/components/ui/CandidateCard.tsx
> +  const [isChecked, setIsChecked] = useState(false);
We will integrate this state management into a ContextProvider once you start working on the follow-up to this PR

2022-02-24 03:04 UTC, amit-sawhney approved these changes
Good work Arman!

2022-02-24 03:04 UTC, amit-sawhney commented on client/src/components/ui/CandidateCard.tsx
> +const CandidateCards: FC<CandidateCardProps> = ({
Excellent find

2022-02-24 03:04 UTC, amit-sawhney commented on client/src/components/ui/MenuTabs.tsx
> +import React, { FC, ReactElement, ReactNode } from 'react';
Most of what you are concerned about will likely take place in the index.tsx file. Or we will create a App.tsx file to handle all of this abstraction. With that being said, I'm not sure what else we could add that would get to cluttered. The reasoning I had was more for as we get to to more mobile or tablet designs, if the tabs change, we wouldn't have to refactor as much. Not sure though 100% though what that is going to look like in the future.

2022-02-24 03:04 UTC, amit-sawhney commented on client/src/styles/styles.scss
> +// body {
Why all of these commented out blocks? I think they need to be deleted?

2022-02-24 04:50 UTC, merged