Store favorite candidates to local storage
hack4impact-uiuc/brink pull request #38
Opened 2022-02-26 03:02 UTC by code-arman

## Summary
Uses React Context to maintain state of all favorited candidates and updates local storage each time new favorite is added
Closes #32 

## Changes

- Make it so favorited candidates persist after closing tab
- Set up folder structure for future contexts and reducers

## Screenshots

(try it out)

2022-02-26 18:58 UTC, amit-sawhney requested changes
Looks really good Arman! Just a few improvements for readability and stuff and it should be good to go. Hopefully we can crank out the other ones really quickly because of this.

2022-02-26 18:58 UTC, amit-sawhney commented on client/src/components/reducers/FavCandidatesReducer.tsx
> +  | { type: 'remove-favorite'; favorite: { id: string; name: string } };
Ideally these objects should be interfaces for readability.

2022-02-26 18:58 UTC, amit-sawhney commented on client/src/components/reducers/FavCandidatesReducer.tsx
> +export const favCandidatesReducer = (state: State, action: Action) => {
In the future are we just going to store id?

2022-02-26 18:58 UTC, amit-sawhney commented on client/src/components/reducers/FavCandidatesReducer.tsx
> +  switch (action.type) {
NIT: add a default here. Even though we are using TypeScript and we should be enforcing the types properly. If something jank ever happens, could be nice to at least have a default condition that tells us something got changed at runtime and it didn't match either of these. Though I'm not even sue that's possible if these are being passed in directly as constants. I still think it is better practice to include defaults in switch statements.

2022-02-26 18:58 UTC, amit-sawhney commented on client/src/components/ui/CandidateCard.tsx
> +import { useFavoritedCandidates } from '../../contexts/FavCandidatesContext';
Needs to be space between the imports and interfaces.

2022-02-26 18:58 UTC, amit-sawhney commented on client/src/components/ui/CandidateCard.tsx
> +  const { state, dispatch } = useFavoritedCandidates();
Though I'm not sure it's totally necessary, I think reducer has a cool, legitimate use case here.

2022-02-26 18:58 UTC, amit-sawhney commented on client/src/components/ui/CandidateCard.tsx
> +    state.some((el) => el.name === name),
Nice use of functional js :)

2022-02-26 18:58 UTC, amit-sawhney commented on client/src/components/ui/CandidateCard.tsx
>  const CandidateCards: FC<CandidateCardProps> = ({
Design wise. Here is something I learned. Testing components that are hooked into a state can be really hard to change. Instead, components should be pure meaning that if you pass in a set of props, the same thing should show up every single time. While I do think it is nice to render a card and let it do it's own checking on the box, I do think you should be aware of this at least sooner rather than later because it was something I learned way to late in the game. 

The solution to this would be create like a defaultChecked prop that is optional and pass in the same logic you used in here.

2022-02-26 18:58 UTC, amit-sawhney commented on client/src/components/ui/CandidateCard.tsx
> +        }}
Could be a little much for an inline function. maybe consider abstracting to a helper function.

2022-02-26 18:58 UTC, amit-sawhney commented on client/src/contexts/FavCandidatesContext.tsx
> +} from '../components/reducers/FavCandidatesReducer';
What do you think about making an index.ts file in the reducers folder so we don't have long import lines for any other reducers that come in the future.

2022-02-26 18:58 UTC, amit-sawhney commented on client/src/contexts/FavCandidatesContext.tsx
> +export type Candidate = { id: string; name: string };
This should be an interface. Refer back to  my explanation of type vs interface.

2022-02-26 18:58 UTC, amit-sawhney commented on client/src/contexts/FavCandidatesContext.tsx
> +export type State = Candidate[];
This is a good use of type though!

2022-02-26 18:58 UTC, amit-sawhney commented on client/src/contexts/FavCandidatesContext.tsx
> +export type Dispatch = (action: Action) => void;
I'm seeing if there is a way to type this that we don't have to disable eslint but this if fine for now

2022-02-26 18:58 UTC, amit-sawhney commented on client/src/contexts/FavCandidatesContext.tsx
> +const FavoritesContextProvider = ({
I believe you just need to type this as const FavoritesContextProvider: FC and it will automatically have children rather than having to inline type children.

2022-02-26 18:58 UTC, amit-sawhney commented on client/src/contexts/FavCandidatesContext.tsx
> +  const localData = localStorage.getItem('favoritedCandidates');
We should probably consider enums/constants for these access keys.

2022-02-26 18:58 UTC, amit-sawhney commented on client/src/contexts/FavCandidatesContext.tsx
> +>(undefined);
Default value is already undefined so you can actually take out `| undefined ` (I think this works within createContext at least and then put nothing in for the default value and it should add the info you are looking

2022-02-27 19:08 UTC, code-arman commented on client/src/contexts/FavCandidatesContext.tsx
> +>(undefined);
Do you mean something like this:

```tsx
const FavoritesContext = createContext<
  { state: State; dispatch: Dispatch } >();
``` 

It gives me errors

2022-02-27 19:09 UTC, code-arman commented on client/src/components/reducers/FavCandidatesReducer.tsx
> +export const favCandidatesReducer = (state: State, action: Action) => {
> In the future are we just going to store id?

Ya, i think just id should work once we have the api hooked in

2022-02-27 19:26 UTC, code-arman commented on client/src/contexts/FavCandidatesContext.tsx
> +} from '../components/reducers/FavCandidatesReducer';
Good idea!

2022-02-27 19:30 UTC, code-arman commented on client/src/contexts/FavCandidatesContext.tsx
> +const FavoritesContextProvider = ({
Neat trick! Thanks!

2022-02-27 19:40 UTC, code-arman commented on client/src/components/ui/CandidateCard.tsx
>  const CandidateCards: FC<CandidateCardProps> = ({
Ok, I added something but not sure if this is exactly what you meant. Let me know

2022-02-27 22:31 UTC, ayanmallik commented on client/src/contexts/FavCandidatesContext.tsx
> +>(undefined);
Streamlined this typescript interface after talking to Amit

2022-02-27 22:35 UTC, ayanmallik approved these changes
Looks great Arman! This initial implementation for caching favorite candidates will prove monumental for storing future information on the app

2022-02-28 00:04 UTC, merged