Create candidate bio page
hack4impact-uiuc/brink pull request #50
Opened 2022-03-08 01:49 UTC by ericcccsliu

## Status:

:construction: In development

## Summary

Closes #48 

## Changes

- Move favorite star to separate component 
- Create candidate bio page 

## Screenshots

2022-03-24 07:35 UTC, amit-sawhney requested changes
Just some questions to address first, but looking good :)

2022-03-24 07:35 UTC, amit-sawhney commented on client/src/components/button/FavoriteButton.tsx
> +import { useFavoritedCandidates } from '../../contexts/FavCandidatesContext';
did we not add this as an export that you could get from just `../contexts`

2022-03-24 07:35 UTC, amit-sawhney commented on client/src/components/button/FavoriteButton.tsx
> +  [key: string]: any;
we fixed this on Sue's PR, but this is bad practice don't do.

2022-03-24 07:35 UTC, amit-sawhney commented on client/src/components/card/CandidateCard.tsx
>    name: string;
Can we generalize this to use the Candidate type now that we have some of those types

2022-03-24 07:35 UTC, amit-sawhney commented on client/src/components/card/CandidateCard.tsx
> -  ...rest
Did you mean to take out rest and not use it anymore?

2022-03-24 07:35 UTC, amit-sawhney commented on client/src/components/link/SocialLink.tsx
> +interface UrlType extends LinkProps {
Rename to SocialLinkProps

2022-03-24 07:35 UTC, amit-sawhney commented on client/src/components/link/SocialLink.tsx
> +        as={urlPairs[candidateUrl.type].icon}
very sexy

2022-03-24 07:35 UTC, amit-sawhney commented on client/src/layout/Navbar.scss
> +@import '../styles/styles.scss';
wait where did this file come from -- i thought we scrapped most of this? Like why is it an entirely new file

2022-03-24 07:35 UTC, amit-sawhney commented on client/src/pages/CandidateBio.tsx
> +// import LinkIcon from '@mui/icons-material/Link';
Delete unused comments

2022-03-24 07:35 UTC, amit-sawhney commented on client/src/pages/CandidateBio.tsx
> +import { SocialLink } from '../components/link/SocialLink';
These should be imported from `../components`

2022-03-24 07:35 UTC, amit-sawhney commented on client/src/utils/constants.ts
> +  BIO: 'bio',
Yea make sure to delete all of the routes that we did this way - I don't think it's cleaner tbh

2022-03-24 07:35 UTC, amit-sawhney commented on yarn.lock
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
Uh did you push a yarn.lock to the root?

2022-03-25 17:53 UTC, ericcccsliu commented on client/src/components/card/CandidateCard.tsx
> -  ...rest
oops just put it back in

2022-03-25 17:59 UTC, ericcccsliu commented on yarn.lock
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
oops maybe

2022-03-26 20:11 UTC, amit-sawhney approved these changes

2022-03-26 20:13 UTC, merged