Setup mobile and desktop layout folders
hack4impact-uiuc/brink pull request #53
Opened 2022-03-10 05:21 UTC by suewee

## Status:

:construction: In development

## Summary

Create a responsive version of the current Navbar. 

Closes #49 

## Changes

- Item 1
- Item 2

## Screenshots

2022-03-15 06:15 UTC, amit-sawhney requested changes
Overall, really great work on this Sue -- I had fun watching the app jump between the 2 designs. Looks like 99% of it is completely functional (one small thing maybe with the menu dropdown which will be tweaked anyway when bryan and jocelyn design it). 

I think it just needs some abstraction and cleanup and then this will be GOLDEN. Thank you for your hard work. you are APPRECIATED ❤️

2022-03-15 06:15 UTC, amit-sawhney commented on client/src/layout/Navbar.tsx
>  export const Navbar = (): ReactElement => {
General repository structure and optimization guide!

I think this file is a bit long. It would be nicer to find a lot of the commonalities between these 2 lists because there should be a lot. and abstract them out to other files. Then in this file -- you could get the address and then pass the address into the components for each of the navbar structures (so that they are pure). 

Also, because you defined the DesktopView and MobileView within the component itself, these actually have to be compiled EVERY time something like `isDesktop`, `isMobile`, `location`, or `address` changes. Instead, these should be abstracted because they really don't require any information within the Navbar component. (this kinda goes with the first comment about abstracting this but this is a performance reason.

2022-03-15 06:15 UTC, amit-sawhney commented on client/src/layout/Navbar.tsx
> +  function DesktopView() {
Still use `const DesktopView = ()` for stuff like this not `function DesktopView()`. Furthermore, even if this was a function that rendered `jsx`, functions in components should be camelCase with a lowercase first letter and more a function name. For example: `const renderDesktopView = () =>`

2022-03-15 06:15 UTC, amit-sawhney commented on client/src/layout/Navbar.tsx
> +          <NavItem marginLeft="25px" width="25%" flexGrow="0.5">
I think the 2 logos have different marginLefts? these should be consistent. This will help when abstracting stuff out.

2022-03-15 06:15 UTC, amit-sawhney commented on client/src/layout/Navbar.tsx
> +      <>
Is this fragment necessary? Also please use `<Fragment>...</Fragment>` from the `react` library instead.

2022-03-15 06:15 UTC, amit-sawhney commented on client/src/layout/Navbar.tsx
> +                  <NavLink href="/help">Help</NavLink>
Are you getting an error where clicking these links aren't doing anything? It just closes the menu but doesn't redirect anywhere? Let me know in if it's just me.

2022-03-15 06:15 UTC, amit-sawhney commented on client/src/layout/Navbar.tsx
> +      style={{ position: 'sticky', top: 0, zIndex: 3 }}
Why did zindex have to go up?

2022-03-15 06:15 UTC, amit-sawhney commented on client/src/layout/Navbar.tsx
> +      {(isDesktop && <DesktopView />) || (isMobile && <MobileView />)}
this is pretty cool though can't lie

2022-03-15 06:15 UTC, amit-sawhney commented on client/src/layout/Navbar.tsx
>  export const Navbar = (): ReactElement => {
Also there actually is a way to make this more optimized if you needed to keep the JSX within the function by doing something like
```tsx
const desktopJsx = useMemo(() => {
    return (
         <nav>pretend this the navbar</nav>
    );
}, []);
```

The dependency array would cause the jsx to rerender every time an item in this dep array was changed -- however there is nothing there so it just loads one time the component mounts.

2022-03-15 06:15 UTC, amit-sawhney commented on client/src/utils/useBreakpoint.tsx
> +const useBreakpoint = ({
There should be a tablet breakpoint just in case we need to identify tablet designs that are unique to tablet.

2022-03-15 06:15 UTC, amit-sawhney commented on client/src/utils/useBreakpoint.tsx
> +import { useWindowSize } from '@reach/window-size';
Can this entire file be placed into the `hook` folder? I feel like it is a better fit there.

2022-03-15 06:15 UTC, amit-sawhney commented on client/src/utils/useBreakpoint.tsx
> +import { useWindowSize } from '@reach/window-size';
don't forget to add it to the `index.ts`

2022-03-17 06:35 UTC, suewee commented on client/src/layout/Navbar.tsx
> +                  <NavLink href="/help">Help</NavLink>
Just fixed it! I had to extend the links to make sure they were covering the entire portion of the menu, they were only clickable via the body of text itself prior to this.

2022-03-17 06:37 UTC, suewee commented on client/src/layout/Navbar.tsx
> +      style={{ position: 'sticky', top: 0, zIndex: 3 }}
The `Home` page's Tab List tends to cover the top two Menu Items otherwise :(

2022-03-17 06:46 UTC, suewee commented on client/src/layout/Navbar.tsx
> +          <NavItem marginLeft="25px" width="25%" flexGrow="0.5">
changed both of them to be 25px!

2022-03-17 06:46 UTC, suewee commented on client/src/layout/Navbar.tsx
> +      <>
oops it wasn't! but the `<Fragment>` note did come in handy still :D

2022-03-17 06:47 UTC, suewee commented on client/src/utils/useBreakpoint.tsx
> +const useBreakpoint = ({
added!

2022-03-17 09:04 UTC, suewee commented on client/src/layout/Navbar.tsx
>  export const Navbar = (): ReactElement => {
I took some parts out and moved them into NavDisplay.tsx -- the Navbar is basically split into three parts: Logo (logic in NavDisplay), Address (in Navbar.tsx), Menu/Links (in NavDisplay). Most of the formatting and styling is in the return portion of Navbar.tsx on purpose so that it's easier to change the Navbar appearance in one centralized file if we ever need to. Let me know if this was along the lines of what you were thinking! If not, I can edit it. :9

2022-03-17 09:05 UTC, suewee commented on client/src/layout/Navbar.tsx
> +  const resizeDelay = 75;
This was to try and avoid constant rerendering if a user is resizing a window!

2022-03-17 09:08 UTC, suewee commented on client/src/layout/Navbar.tsx
> +  };
When trying to fix the excessive right margins issue, I realized it was because setting maxWidth complicates it a lot. Using a proportion related to the current window width was the only clean way I could come up with!

2022-03-17 09:09 UTC, suewee commented on client/src/layout/Navbar.tsx
> +      style={{ position: 'sticky', top: 0, zIndex: 3 }}
I added a comment on your last one, but for convenience I'll put it here too! Basically with a z-index of 2, the TabsList was covering the top 2 menu items, but increasing it to 3 fixed it.

2022-03-17 09:11 UTC, suewee commented on client/src/layout/Navbar.tsx
> +                  maxWidth="inherit"
I had to pass down the maxWidth because the outermost layer renders the size in the big picture of the navbar but the innermost nested Text needs it to know where to truncate the address.

2022-03-17 20:14 UTC, amit-sawhney approved these changes
This looks super clean Sue! Few style things left but functionality wise this is super impressive and looks like it is really well thought out AND optimized.

2022-03-17 20:14 UTC, amit-sawhney commented on client/src/components/nav/NavDisplay.tsx
> +import { NavItem, NavLink } from '..';
I have seen this happen when you auto import. Idk how to feel about it tbh. We did it on ssw but I think it may be better just to import it from a more clear path. but this is insanely picky. it just looks weird to import from '..'

2022-03-17 20:14 UTC, amit-sawhney commented on client/src/layout/Navbar.tsx
> +  };
this is insanely cool though -- i like it :)

2022-03-17 20:14 UTC, amit-sawhney commented on client/src/layout/Navbar.tsx
> +    };
i was just trying to figure if there was a way to do this without doing `window.removeEventListener`-- because it isn't really `React-y`

2022-03-17 21:58 UTC, suewee commented on client/src/layout/Navbar.tsx
> +    };
I found this other version that uses `clearTimeout` and `setTimeout`, is this better?

2022-03-18 04:47 UTC, ayanmallik approved these changes
Really awesome work Sue! It’s super cool to drag the window size and see the responsiveness in full effect

2022-03-18 04:47 UTC, ayanmallik commented on client/src/components/nav/NavLogo.tsx
> +export const NavLogo: FC<ImageProps> = ({ ...rest }): ReactElement => (
Nice job utilizing the NavLink component for your Brink logo link!

2022-03-19 00:52 UTC, merged