Add breadcrumbs
hack4impact-uiuc/brink pull request #55
Opened 2022-03-10 23:22 UTC by code-arman

## Status:

:construction: In development

## Summary

Closes #<Issue Number>

## Changes

- Item 1
- Item 2

## Screenshots

2022-03-25 19:18 UTC, code-arman commented on client/src/api/_fakeApi.ts
> +const MIN_DELAY = 1;
lol the mock api was too slow4me

2022-03-26 03:15 UTC, ayanmallik requested changes
Overall, great job Arman! The finished product is so cool to interact with - especially because of how clean your styles are. This is one of the coolest PR's I've ever seen based on the sheer functionality that you've built out on the Election Guide. Awesome job man!

Let me know if you have any questions about my feedback, and let's also wait to hear what Amit has to say.

2022-03-26 03:15 UTC, ayanmallik commented on client/src/pages/tab/ballot/BallotListWrapper.tsx
> +        {`${pluralize(countDescriptor, length, true)}`}
Nice job utilizing the pluralize package to handle the singular version of each noun. In general, this feature is super cool because it alerts the screen reader however many links are on the screen making our ballot page super accessible.

2022-03-26 03:15 UTC, ayanmallik commented on client/src/pages/tab/ballot/BallotContent.tsx
> +  countDescriptor: 'categories' | 'candidates' | 'races';
Now I see why you wanted to utilize a type picker - great idea!

2022-03-26 03:15 UTC, ayanmallik commented on client/src/pages/tab/ballot/Candidates.tsx
> +      const res = await BallotReadyAPI.getPositions(1, 1, 'fakeId');
This interaction with BallotReady will be heavily simplified once we build out the hook for the positions endpoint.

2022-03-26 03:15 UTC, ayanmallik commented on client/src/pages/tab/ballot/Elections.tsx
> +  const elections = useElections();
I love how simple this elections page is by using the corresponding hook that Amit built out!

2022-03-26 03:15 UTC, ayanmallik commented on client/src/pages/tab/ballot/Positions.tsx
> +  const [position, setPosition] = useState<Position[]>();
Can we call this variable `positions` since it represents an array?

2022-03-26 03:15 UTC, ayanmallik commented on client/src/pages/tab/ballot/Races.tsx
> +  const sortOrder: any = {
Nice job implementing the sort feature for the races page (even though you didn't use my technique lol)!

2022-03-26 03:15 UTC, ayanmallik commented on client/src/pages/tab/ballot/Title.tsx
> +const Title = ({ name, date, display, subheading }: TitleProps) => (
Great job abstracting out the election title display into it's own component! Love to see some good old modularity

2022-03-26 03:15 UTC, ayanmallik commented on client/src/utils/constants.ts
> +export const TAB_LINKS = {
I think we're going to move away from these defined routes but let's refer to Amit for that decision.

2022-03-26 03:15 UTC, ayanmallik commented on client/src/utils/helpers.ts
> +export const formatDate = (date: string) => {
Great job building out multiple helper functions that we can utilize across the codebase!

2022-03-26 03:15 UTC, ayanmallik commented on client/src/utils/helpers.ts
> +    'Novoember',
Typo lmao

2022-03-26 03:20 UTC, ayanmallik commented
Encountered a bug: should say races instead of candidates on this page
<img width="890" alt="image" src="https://user-images.githubusercontent.com/45826922/160222868-696ddbb6-f15a-4dc4-90b7-742739b541c7.png">

2022-03-26 03:40 UTC, code-arman commented on client/src/utils/helpers.ts
> +    'Novoember',
Great catch!

2022-03-26 03:40 UTC, code-arman commented on client/src/utils/constants.ts
> +export const TAB_LINKS = {
Sounds good, i kinda just assumed some stuff was lost in previous merges so i added it back

2022-03-26 03:43 UTC, code-arman commented on client/src/app.tsx
> +        path={createPath(APP_ROUTE.HOME)}
Honestly not sure. I remember I mentioned this but idk if that was being done. I do remember when pulling from main, these changes were gone, but i thought it was an accident that it got deleted

2022-03-26 03:48 UTC, code-arman commented
> Encountered a bug: should say races instead of candidates on this page <img alt="image" width="890" src="https://user-images.githubusercontent.com/45826922/160222868-696ddbb6-f15a-4dc4-90b7-742739b541c7.png">

Great catch again haha

2022-03-26 18:59 UTC, amit-sawhney requested changes
Few general comments,

- you left a yarn.lock
- you left a package-lock.json -- this comes from npm install 
- Delete empty files

Looks really good. Sorry this PR got so big.

2022-03-26 18:59 UTC, amit-sawhney commented on client/src/api/_fakeApi.ts
> +const MIN_DELAY = 1;
LOL fair

2022-03-26 18:59 UTC, amit-sawhney commented on client/src/app.tsx
> +import VoterFAQ from './pages/tab/VoterFAQ';
Add a space between imports and the code

2022-03-26 18:59 UTC, amit-sawhney commented on client/src/app.tsx
> +import VoterFAQ from './pages/tab/VoterFAQ';
Generally, we should be importing from `../pages` not each level with pages. Use `index.ts` for this

2022-03-26 18:59 UTC, amit-sawhney commented on client/src/app.tsx
> +        path={createPath(APP_ROUTE.HOME)}
Yea scrap APP_ROUTE from everything. We won't use it

2022-03-26 18:59 UTC, amit-sawhney commented on client/src/components/card/CandidateCard.tsx
> +  id: string;
Honestly this should be a candidate type rather than passing in name and id separately.

2022-03-26 18:59 UTC, amit-sawhney commented on client/src/pages/tab/ballot/BallotContent.tsx
> +};
What does this do

2022-03-26 18:59 UTC, amit-sawhney commented on client/src/pages/tab/ballot/BallotContent.tsx
> +import BallotListWrapper from './BallotListWrapper';
Naming could probably be improved on these? is this not just a BallotList.

2022-03-26 18:59 UTC, amit-sawhney commented on client/src/pages/tab/ballot/BallotContent.tsx
> +import BallotListWrapper from './BallotListWrapper';
Also if this is a list component -- it should be in the lists folder in components

2022-03-26 18:59 UTC, amit-sawhney commented on client/src/pages/tab/ballot/BallotContent.tsx
> +type PickByType<T, Value> = {
prefer this to be an interface

2022-03-26 18:59 UTC, amit-sawhney commented on client/src/pages/tab/ballot/BallotContent.tsx
> +  countDescriptor: 'categories' | 'candidates' | 'races';
where did this come from?

2022-03-26 18:59 UTC, amit-sawhney commented on client/src/pages/tab/ballot/BallotContent.tsx
> +            key={index}
This is an anti-pattern. use the position ID or some unique information in position. if there is none, get back to me. But using index as a key is bad practice.

2022-03-26 18:59 UTC, amit-sawhney commented on client/src/pages/tab/ballot/BallotListWrapper.tsx
> +import pluralize from 'pluralize';
How big is this package? can we just hardcode the singular versions of the package.

2022-03-26 18:59 UTC, amit-sawhney commented on client/src/pages/tab/ballot/BallotListWrapper.tsx
> +const BallotListWrapper: FC<BallotListWrapperProps> = ({
Wait ignore my earlier comment -- I see this wraps AROUND a list

2022-03-26 18:59 UTC, amit-sawhney commented on client/src/pages/tab/ballot/BallotListWrapper.tsx
> +  <>
Use Fragment explicitly from `React`

2022-03-26 18:59 UTC, amit-sawhney commented on client/src/pages/tab/ballot/Candidates.tsx
> +  }
Should this be in a function.

2022-03-26 18:59 UTC, amit-sawhney commented on client/src/pages/tab/ballot/Candidates.tsx
> +      }
Do we want to do anything with this

2022-03-26 18:59 UTC, amit-sawhney commented on client/src/pages/tab/ballot/Candidates.tsx
> +                />
Can we abstract this

2022-03-26 18:59 UTC, amit-sawhney commented on client/src/pages/tab/ballot/Elections.tsx
> +import Breadcrumbs from '../../../components/ui/Breadcrumbs';
no default export here.

2022-03-26 18:59 UTC, amit-sawhney commented on client/src/pages/tab/ballot/Races.tsx
> +  useEffect(() => {
add space

2022-03-26 18:59 UTC, amit-sawhney commented on client/src/pages/tab/ballot/Races.tsx
> +  const sortOrder: any = {
you don't need to type this I don't think and if you do,

look at Record

2022-03-26 18:59 UTC, amit-sawhney commented on client/src/pages/tab/ballot/Races.tsx
> +            ),
In general, if we are rending .map stuff it should probably inside of some sort list for screen readers.

2022-03-26 18:59 UTC, amit-sawhney commented on client/src/utils/helpers.ts
> +};
While cool, this could probably be done by just using the full day.

2022-03-26 18:59 UTC, amit-sawhney commented on client/src/utils/helpers.ts
> +    .join(' ');
Is this capitalizing every word?

2022-03-27 05:42 UTC, code-arman commented on client/src/pages/tab/ballot/BallotContent.tsx
> +type PickByType<T, Value> = {
Is that possible for this typa thing? Not sure how to do it

2022-03-27 05:48 UTC, code-arman commented on client/src/pages/tab/ballot/BallotContent.tsx
> +};
Creates a type with only attributes of the specified type.

So if the type was like:

```tsx
interface Dog {
name: string
bestieName: string
age: number
friends: string[]
isOld = boolean
``` 
and we do 

```tsx
type Hey =  PickByType<Dog, string>
```
it becomes 
```
type Hey {
name: string
bestieName: string
}
```
since those are the only two string types

2022-03-27 05:49 UTC, code-arman commented on client/src/pages/tab/ballot/BallotContent.tsx
> +  countDescriptor: 'categories' | 'candidates' | 'races';
Not sure if this is what ur referring to but https://stackoverflow.com/questions/46583883/typescript-pick-properties-with-a-defined-type

2022-03-27 05:53 UTC, code-arman commented on client/src/pages/tab/ballot/BallotListWrapper.tsx
> +import pluralize from 'pluralize';
https://github.com/plurals/pluralize/blob/master/pluralize.js

it's pretty long and gross. there are a lotta edge cases with pluralization

2022-03-27 06:01 UTC, code-arman commented on client/src/pages/tab/ballot/Races.tsx
> +  const sortOrder: any = {
It does make me. Record is clutch!

2022-03-27 06:25 UTC, code-arman commented on client/src/pages/tab/ballot/Races.tsx
> +            ),
I agree that this should be in ul and li's. When I make it a list instead of a fragment, the centering gets really messed up, and I couldnt fix it after playing around with it for a bit.

2022-03-27 06:29 UTC, code-arman commented on client/src/utils/helpers.ts
> +    .join(' ');
Capitalizes first letter of every word except when it has a '.' in it. I was trying to find a good way to handle capitalization for words like "U.S Senator", cuz otherwise it shows up as "U.s Senator" and looks weird

2022-03-27 06:49 UTC, code-arman commented on client/src/components/card/CandidateCard.tsx
> +  id: string;
Totally agree!

2022-03-27 07:02 UTC, code-arman commented on client/src/pages/tab/ballot/Candidates.tsx
> +      }
Added `throw new Error(res.data.message)`

2022-03-28 15:50 UTC, amit-sawhney approved these changes
Looks really good Arman! Thanks for the quick turn around on the last review. 

Two high level comments: 
- Would it be possible to keep the tabs and breadcrumbs sticky on the Ballot tab? At least the tabs for sure. They scroll and disappear under the navbar now
- The responsiveness on the first page of the ballot seems to be a little off

After those are fixed, this looks good for me

2022-03-28 15:50 UTC, amit-sawhney commented on client/src/pages/Home.tsx
>    }, [pathname]);
I just realized couldn't we just make an object like

```tsx
const activeIndex = {
    '/home/checklist': 0,
    '/home/faq/': 1,
    '/home/ballot': 2,
}

const index = activeIndex[pathname]
```

2022-03-28 15:50 UTC, amit-sawhney commented on client/src/pages/Home.tsx
> +      case 'ballot':
Is this supposed to be just ballot? rather than `/home/ballot`

2022-03-28 15:50 UTC, amit-sawhney commented on client/src/pages/tab/ballot/BallotContent.tsx
> +type RequiredStringTypesOfPosition = PickByType<Position, string>;
I see now! really cool

2022-03-28 15:50 UTC, amit-sawhney commented on client/src/pages/tab/ballot/BallotContent.tsx
> +};
very nice

2022-03-28 15:50 UTC, amit-sawhney commented on client/src/pages/tab/ballot/Candidates.tsx
> +import Title from './Title';
Curious to your thoughts on this. When i started using a `pages` and `components` folder, I found that there could be a little bit of a fuzzy distinction between what goes in each. It seems like you are keeping Page specific components  within this folder. Even if they are pretty specific to the page, should it still be added in some way to the components folder? 

Just curious to hear your thoughts

2022-03-28 15:50 UTC, amit-sawhney commented on client/src/pages/tab/ballot/Races.tsx
> +import { formatDate } from '../../../utils/helpers';
These are getting kind of long. Instead of going `pages/tab/ballot` could we remove the ballot layer? And just name the other files a little better to be prefixed with Ballot

2022-03-28 15:50 UTC, amit-sawhney commented on client/src/pages/tab/ballot/Races.tsx
> +          (position, index, self) =>
woah i didn't realize there was a 3rd argument that you could use

2022-03-28 15:50 UTC, amit-sawhney commented on client/src/utils/helpers.ts
> +  return `${days}`;
I think you can just return `days`

2022-03-28 15:50 UTC, amit-sawhney commented on client/src/utils/helpers.ts
> +    .join(' ');
ahhh I understand. Yea that's fine. good solution

2022-03-28 16:11 UTC, amit-sawhney commented on client/src/pages/tab/ballot/Candidates.tsx
> +      }
Oh I see why u added these now

2022-03-28 21:28 UTC, code-arman commented on client/src/pages/tab/ballot/BallotContent.tsx
> +type PickByType<T, Value> = {
yeah, didnt work when i replaced the word type with interface, so ill keep as is

2022-03-28 21:32 UTC, code-arman commented on client/src/pages/tab/ballot/BallotListWrapper.tsx
> +import pluralize from 'pluralize';
I was just thinking that in the future, wouldnt there be other parts of the app that we'd want to pluralize? If this is the only place, then I can just do this.

2022-03-28 21:34 UTC, code-arman commented on client/src/contexts/ElectionsContext.tsx
> +      throw new Error(res.data.message);
lol i accidentally modified that file. my bad

2022-03-28 21:36 UTC, code-arman commented on client/src/pages/Home.tsx
> +      case 'ballot':
Yea tru `/home/ballot` is more specific! Changing to that !

2022-03-28 21:38 UTC, code-arman commented on client/src/utils/helpers.ts
> +  return `${days}`;
Haha, agreed!

2022-03-28 21:40 UTC, code-arman commented on client/src/pages/tab/ballot/Races.tsx
> +        throw new Error(res.data.message);
I did this sorta as a placeholder. And also, for when we're debugging and something fails, we can check console and see that an error was thrown. 

I agree that having an isError state would be better since it would allow us to conditionally render an error message

2022-03-28 21:49 UTC, code-arman commented on client/src/pages/Home.tsx
>    }, [pathname]);
I was trippin. I actually need the last one to check if pathname.includes 'home/ballot'. So im gonna do the useMemo way as before

2022-03-28 21:52 UTC, code-arman commented on client/src/pages/tab/ballot/Candidates.tsx
> +import Title from './Title';
I see what you're saying. That was an accident. I do agree that files like BallotListWrapper and Title should be in the components folder. Would you agree that the rest of the files in that folder should stay as is?

2022-03-28 21:57 UTC, code-arman commented on client/src/pages/tab/ballot/Candidates.tsx
> +import Title from './Title';
In terms of where these should go. I'm going to make a ballot folder in the components directory and put these there. Do you think they should go somewhere else like inside of UI?

2022-03-29 02:27 UTC, ayanmallik approved these changes
Looks fantastic Arman! Thanks for fixing up the formatting and the stickiness of the tabs/breadcrumb. Everything runs smoothly on my end - awesome job overall!

2022-03-29 06:29 UTC, merged