Set up starting files
hack4impact-uiuc/brink pull request #94
Opened 2022-04-19 16:04 UTC by ericcccsliu

## Status:

:construction: In development

## Summary

Closes [#81](https://github.com/hack4impact-uiuc/brink/issues/81)

## Changes

- Item 1
- Item 2

## Screenshots

2022-04-27 22:35 UTC, ayanmallik approved these changes
Fantastic work, Eric! It's incredible to see the voting checklist come together. I remember when you first took on that checklist feature with React Context and it's crazy now to see that all interact with real data from Contentful. Awesome job overall owning this feature from start to finish!

2022-04-27 22:35 UTC, ayanmallik commented on client/src/api/checkItems.ts
> +export const checkItems: CheckItemsType = {
Great find fetching this data from TableXI!

2022-04-27 22:35 UTC, ayanmallik commented on client/src/app.tsx
> +      return <></>;
Let's return a Chakra UI Spinner component when the Checklist is still loading: `return <Spinner m={1} />;`

2022-04-27 22:35 UTC, ayanmallik commented on client/src/components/card/VotingMethodCard.tsx
> +      </Text>{' '}
Let's remove this suffix blank string `{' '}` - if this is used for styling, we probably want to refactor this logic using CSS properties.

2022-04-27 22:35 UTC, ayanmallik commented on client/src/components/card/VotingMethodCard.tsx
>      >
Awesome job refactoring these voting method cards to support the new radio button logic!

2022-04-27 22:35 UTC, ayanmallik commented on client/src/components/ui/CheckBox.tsx
> +      }
Great job handling all the various trigger effects on the voting checklist for each of the buttons retrieved from Contentful!

2022-04-27 22:35 UTC, ayanmallik commented on client/src/pages/tab/BallotRaces.tsx
> +      ? positions.sort((a, b) => sortOrder[a.level] - sortOrder[b.level])
Great job simplifying this function!

2022-04-27 22:35 UTC, ayanmallik commented on client/src/pages/tab/checklist/ElectionChecklist.tsx
> +  }, [storedItems, votingMethod]);
Awesome job computing the number of checked items using the `reduce()` function. One thing I recommend is abstracting this logic outside of the `setCount()` so that it looks something like this:

```
newCount = votingMethod
        ? todos[votingMethod].reduce(
            (count, todo) =>
              (count += todo.data.filter((item) =>
                storedItems.includes(item),
              ).length),
            0,
          )
        : 0

setCount(newCount);
```

2022-04-28 03:23 UTC, ericcccsliu commented on client/src/app.tsx
> +      return <></>;
k

2022-04-28 03:30 UTC, amit-sawhney requested changes
Work on the mobile responsiveness on this PR. Buttons tend to be inconsistent on mobile and wrapping tends to be wrong

2022-04-28 03:30 UTC, amit-sawhney commented on client/src/api/checkItems.ts
> +import { VotingMethodType } from '../types/contentful';
This should probably be in a constants folder most likely

2022-04-28 03:30 UTC, amit-sawhney commented on client/src/components/card/ElectionCard.tsx
> +  console.log(election);
Remove console.log

2022-04-28 03:30 UTC, amit-sawhney commented on client/src/components/ui/CheckBox.tsx
> +      <VStack alignItems="start" paddingLeft="37px" spacing="7px" width="100%">
Will this be responsive? with the paddings

2022-04-28 03:30 UTC, amit-sawhney commented on client/src/components/ui/CheckBox.tsx
>  export const CheckBox: FC<CheckBoxProps> = ({
On a mobile view this isn't super responsive at all. We should probably address this before merging.

2022-04-28 03:30 UTC, amit-sawhney commented on client/src/pages/tab/checklist/ElectionChecklist.tsx
> +        : 0,
this doesn't need to be a ternary, abstract the votingMethod undefined checkoutside and have 2 setCounts

2022-04-28 03:43 UTC, ericcccsliu commented on client/src/components/ui/CheckBox.tsx
> +      <VStack alignItems="start" paddingLeft="37px" spacing="7px" width="100%">
no ❤️

2022-04-28 04:23 UTC, amit-sawhney approved these changes
legend

2022-04-28 04:24 UTC, merged